#! /bin/bash
#VBoxHeadless --startvm "ubuntu"

#ip_addr=192.168.1.72
ip_addr=10.16.74.55

while true; do
echo "c- compile  r- run  d- clean k- reset filename q- quit e-echo and read p- print "
read -a input -r -p ""
echo ${input[0]}


if [ -z "$filename" ]; then
  filename=${input[1]}
  mod_filename=${filename: :-2}
  ko_filename="$mod_filename"".ko"
fi

echo "Running on $filename"
case  ${input[0]}  in
  c)
            sshpass -p "123456" ssh root@$ip_addr 'mkdir -p /root/compile-module || true'
            sshpass -p "123456" ssh root@$ip_addr rm -f /root/compile-module/*.c /root/compile-module/Makefile
            sshpass -p "123456" scp $filename root@$ip_addr:/root/compile-module
            sshpass -p "123456" scp Makefile root@$ip_addr:/root/compile-module
            sshpass -p "123456" ssh root@$ip_addr make -C /root/compile-module MODULE_NAME=$filename
            sshpass -p "123456" ssh root@$ip_addr ls -la /root/compile-module
     		    ;;
  r)
            sshpass -p "123456" ssh root@$ip_addr dmesg -c >/dev/null
            sshpass -p "123456" ssh root@$ip_addr insmod /root/compile-module/$ko_filename
            sshpass -p "123456" ssh root@$ip_addr dmesg

                    ;;

  d)
            sshpass -p "123456" ssh root@$ip_addr dmesg -c >/dev/null
            sshpass -p "123456" ssh root@$ip_addr rmmod /root/compile-module/$ko_filename
            sshpass -p "123456" ssh root@$ip_addr make -C /root/compile-module clean

                ;;
  m)
            sshpass -p "123456" ssh root@$ip_addr mknod /dev/chardev c 243 0
     		             ;;
  k)
                             unset filename                              ;;

  p)
          sshpass -p "123456" ssh root@$ip_addr dmesg                   ;;

  q)
           break
    		             ;;

  *)
esac

done
